#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=10
STOP=15
 
start() {        
	echo start
	# macaddr=$(cat /sys/class/net/eth0/address | awk '{print toupper($0)}' | sed 's/\://g') 
	# echo "MAC address from EEPROM: $macaddr" 
	# echo -e "indestroom\nlinuxpassword\nlinuxpassword" | passwd
}                 
 
stop() {          
	echo stop
	# commands to kill application 
}
